---
# Installs Postgresql
# Alex Knight
- name: Add a postgres group
  group: name={{ postgres_group }}

- name: Add a postgres user
  user: name={{ postgres_user }} group={{ postgres_group }} home={{ postgres_user_home }}

- name: Install postgresql server
  yum: name=postgresql-server state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install postgresql contrib
  yum: name=postgresql-contrib state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install postgresql server
  apt: name=postgresql state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install postgresql contrib
  apt: name=postgresql-contrib state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Initialize Postgres DB
  command: postgresql-setup initdb
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Start Postgres DB
  command: systemctl start postgresql
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
